name: C++ CI

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: updatesystem
      run: sudo apt-get update && sudo apt-get upgrade && sudo apt-get autoremove
    - name: installdeps
      run: sudo sh install-deps.sh && sudo sh build-install-build-deps.sh
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: make

  build-windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, windows-2016]
    
    steps:
    - uses: actions/checkout@v1
    - name: installdeps
      shell: bash
      run: bash install-deps.sh && bash build-install-build-deps.sh
    - name: configure
      shell: bash
      run: mkdir build && cd build && cmake ..
    - name: build
      shell: bash
      run: make
